In [1]:
from pyspark.ml import feature
from pyspark.ml import clustering
from pyspark.ml import Pipeline
from pyspark.sql import functions as fn
import numpy as np
from pyspark.sql import SparkSession
from pyspark.ml import feature, regression, evaluation, Pipeline
from pyspark.sql import functions as fn, Row
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from pyspark.sql import functions as sf
from pyspark.ml.feature import CountVectorizer
from pyspark.ml.feature import IDF
from pyspark.ml.feature import RegexTokenizer
import requests
from pyspark.ml.feature import StopWordsRemover
from pyspark.sql.functions import concat, col, lit, lower
from pyspark.sql.functions import isnan, when, count, col, isnull
from pyspark.sql.functions import concat_ws
from  pyspark.sql.functions import abs
# seting master("local[*]") enables multicore processing on all available logical cores on your machine
spark = SparkSession.builder.master("local[*]").getOrCreate()
sc = spark.sparkContext

In [2]:
# Do not delete or change this cell

import os

# Define a function to determine if we are running on data bricks
# Return true if running in the data bricks environment, false otherwise
def is_databricks():
    # get the databricks runtime version
    db_env = os.getenv("DATABRICKS_RUNTIME_VERSION")
    
    # if running on data bricks
    if db_env != None:
        return True
    else:
        return False

# Define a function to read the data file.  The full path data file name is constructed
# by checking runtime environment variables to determine if the runtime environment is 
# databricks, or a student's personal computer.  The full path file name is then
# constructed based on the runtime env.
# 
# Params
#   data_file_name: The base name of the data file to load
# 
# Returns the full path file name based on the runtime env
#
def get_training_filename(data_file_name):    
    # if running on data bricks
    if is_databricks():
        # build the full path file name assuming data brick env
        full_path_name = "/FileStore/tables/%s" % data_file_name
    # else the data is assumed to be in the same dir as this notebook
    else:
        # Assume the student is running on their own computer and load the data
        # file from the same dir as this notebook
        full_path_name = data_file_name
    
    # return the full path file name to the caller
    return full_path_name

In [3]:
airlines_df = spark.read.csv(get_training_filename('airlines.csv'), header=True, inferSchema=True)
airports_df = spark.read.csv(get_training_filename('airports.csv'), header=True, inferSchema=True)
flights_df = spark.read.csv(get_training_filename('flights.csv'), header=True, inferSchema=True)

In [4]:
flights_df = flights_df.select('MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT', 'SCHEDULED_DEPARTURE', 'DEPARTURE_DELAY', 'DISTANCE', 'SCHEDULED_ARRIVAL', 'ARRIVAL_DELAY', 'CANCELLED')

flights_df = flights_df.fillna( { 'DEPARTURE_DELAY':0 } )

from pyspark.ml.feature import Bucketizer
bucketizer = Bucketizer(splits=[ 0, 100, 1000, float('Inf') ],inputCol="DISTANCE", outputCol="Distance_Bucket")
flights_df = bucketizer.setHandleInvalid("keep").transform(flights_df)

from pyspark.sql.functions import udf
from pyspark.sql.types import *

t = {0.0:"Short", 1.0: "Medium", 2.0:"Long"}
udf_foo = udf(lambda x: t[x], StringType())
flights_df = flights_df.withColumn("Flight_Distance", udf_foo("Distance_Bucket"))

from pyspark.ml.feature import StringIndexer

indexer = StringIndexer(inputCol="AIRLINE", outputCol="Airline_Numeric").fit(flights_df)
flights_df = indexer.transform(flights_df)

from pyspark.ml.feature import OneHotEncoder
encoder = OneHotEncoder(inputCol="Airline_Numeric", outputCol="Airline_OHE")
flights_df= encoder.transform(flights_df)

indexer = StringIndexer(inputCol="ORIGIN_AIRPORT", outputCol="OA_Numeric").fit(flights_df)
flights_df = indexer.transform(flights_df)

encoder = OneHotEncoder(inputCol="OA_Numeric", outputCol="Origin_Airport_OHE")
flights_df= encoder.transform(flights_df)

indexer = StringIndexer(inputCol="DESTINATION_AIRPORT", outputCol="DA_Numeric").fit(flights_df)
flights_df = indexer.transform(flights_df)

encoder = OneHotEncoder(inputCol="DA_Numeric", outputCol="Destination_Airport_OHE")
flights_df= encoder.transform(flights_df)

flights_df = flights_df.drop('ARRIVAL_DELAY')


In [5]:
flights_df.printSchema()

root
-- MONTH: integer (nullable = true)
-- DAY: integer (nullable = true)
-- DAY_OF_WEEK: integer (nullable = true)
-- AIRLINE: string (nullable = true)
-- ORIGIN_AIRPORT: string (nullable = true)
-- DESTINATION_AIRPORT: string (nullable = true)
-- SCHEDULED_DEPARTURE: integer (nullable = true)
-- DEPARTURE_DELAY: integer (nullable = false)
-- DISTANCE: integer (nullable = true)
-- SCHEDULED_ARRIVAL: integer (nullable = true)
-- ARRIVAL_DELAY: integer (nullable = true)
-- CANCELLED: integer (nullable = true)
-- Distance_Bucket: double (nullable = true)
-- Flight_Distance: string (nullable = true)
-- Airline_Numeric: double (nullable = false)
-- Airline_OHE: vector (nullable = true)
-- OA_Numeric: double (nullable = false)
-- Origin_Airport_OHE: vector (nullable = true)
-- DA_Numeric: double (nullable = false)
-- Destination_Airport_OHE: vector (nullable = true)

In [6]:
flights_df.select([count(when(isnull(c), c)).alias(c) for c in flights_df.columns]).show()

+-----+---+-----------+-------+--------------+-------------------+-------------------+---------------+--------+-----------------+---------+---------------+---------------+---------------+-----------+----------+------------------+----------+-----------------------+
MONTH|DAY|DAY_OF_WEEK|AIRLINE|ORIGIN_AIRPORT|DESTINATION_AIRPORT|SCHEDULED_DEPARTURE|DEPARTURE_DELAY|DISTANCE|SCHEDULED_ARRIVAL|CANCELLED|Distance_Bucket|Flight_Distance|Airline_Numeric|Airline_OHE|OA_Numeric|Origin_Airport_OHE|DA_Numeric|Destination_Airport_OHE|
+-----+---+-----------+-------+--------------+-------------------+-------------------+---------------+--------+-----------------+---------+---------------+---------------+---------------+-----------+----------+------------------+----------+-----------------------+
 0| 0| 0| 0| 0| 0| 0| 0| 0| 0| 0| 0| 0| 0| 0| 0| 0| 0| 0|
+-----+---+-----------+-------+--------------+-------------------+-------------------+---------------+--------+-----------------+---------+---------------+---------------+---------------+-----------+----------+------------------+----------+-----------------------+

In [7]:
from pyspark.sql import functions as fn
flights_df.groupBy('CANCELLED').agg(fn.count('*')).show()

+---------+--------+
CANCELLED|count(1)|
+---------+--------+
 1| 89884|
 0| 5729195|
+---------+--------+

In [8]:
training_df, testing_df = flights_df.randomSplit([0.9, 0.1], seed=5)

In [9]:
major_df = training_df.filter(col("CANCELLED") == 0)
minor_df = training_df.filter(col("CANCELLED") == 1)

In [10]:
ratio = major_df.count()/minor_df.count()
print(ratio)

63.658002938670684

In [11]:
sampled_majority_df = major_df.sample(False, 3/ratio, seed=5)
combined_df_2 = sampled_majority_df.unionAll(minor_df)

In [12]:
combined_df_2.groupBy('CANCELLED').agg(fn.count('*')).show()

+---------+--------+
CANCELLED|count(1)|
+---------+--------+
 1| 80989|
 0| 81086|
+---------+--------+

In [13]:
from pyspark.ml.feature import VectorAssembler

va = VectorAssembler(
    inputCols=["MONTH", "DAY", "DAY_OF_WEEK", "Airline_OHE", "Origin_Airport_OHE", "Destination_Airport_OHE", "SCHEDULED_DEPARTURE", "Distance_Bucket", "SCHEDULED_ARRIVAL"], outputCol="features")

In [14]:
inputColumns = ["MONTH", "DAY", "DAY_OF_WEEK", "Airline_OHE", "Origin_Airport_OHE", "Destination_Airport_OHE", "SCHEDULED_DEPARTURE", "Distance_Bucket", "SCHEDULED_ARRIVAL"]

In [15]:
from pyspark.ml.classification import LogisticRegression, RandomForestClassifier
from pyspark.ml import Pipeline
from pyspark.ml.evaluation import BinaryClassificationEvaluator
from pyspark.ml.classification import GBTClassifier
from pyspark.ml.tuning import CrossValidator, ParamGridBuilder
from pyspark.ml.tuning import CrossValidatorModel
bce = BinaryClassificationEvaluator(labelCol='CANCELLED', metricName='areaUnderROC')
from pyspark.ml import evaluation

In [16]:
lr = LogisticRegression(featuresCol='features', labelCol='CANCELLED', regParam=0.2, elasticNetParam=0.1, threshold=0.45, thresholds=[0.55, 0.45])
lr_pipeline = Pipeline(stages=[va, lr])
lr_model = lr_pipeline.fit(combined_df_2)
lr_transform = lr_model.transform(testing_df)

In [17]:
predictions_train = lr_transform
y_true = predictions_train.select(['CANCELLED']).collect()
y_pred = predictions_train.select(['prediction']).collect()

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_true, y_pred))
confusion_matrix(y_true, y_pred)

precision recall f1-score support

 0 0.98 1.00 0.99 573597
 1 0.14 0.01 0.02 8895

 micro avg 0.98 0.98 0.98 582492
 macro avg 0.56 0.50 0.51 582492
weighted avg 0.97 0.98 0.98 582492

Out[44]: array([[573030, 567],
 [ 8800, 95]])

In [18]:
plt.figure(figsize=(10,6))
plt.plot([0, 1], [0, 1], 'r--')
plt.scatter(lr_model.stages[-1].summary.roc.select('FPR').collect(),
            lr_model.stages[-1].summary.roc.select('TPR').collect())
plt.title('ROC Scatter Plot Flight Cancellation : TPR/FPR')
plt.xlabel('FPR')
plt.ylabel('TPR')
display()

In [19]:
lr_bce = BinaryClassificationEvaluator(labelCol='CANCELLED', metricName='areaUnderROC')
lr_bce.evaluate(lr_transform)

In [20]:
lr_evaluator_accuracy = evaluation.MulticlassClassificationEvaluator(labelCol="CANCELLED", metricName="accuracy")
lr_evaluator_accuracy.evaluate(lr_transform)

In [21]:
rf = RandomForestClassifier(featuresCol='features', labelCol='CANCELLED')
rf_pipeline = Pipeline(stages=[va, rf])
rf_model = rf_pipeline.fit(combined_df_2)
rf_transform = rf_model.transform(testing_df)

In [22]:
predictions_train = rf_transform
y_true = predictions_train.select(['CANCELLED']).collect()
y_pred = predictions_train.select(['prediction']).collect()

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_true, y_pred))
confusion_matrix(y_true, y_pred)

/databricks/python/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
 'precision', 'predicted', average, warn_for)
/databricks/python/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
 'precision', 'predicted', average, warn_for)
/databricks/python/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
 'precision', 'predicted', average, warn_for)
 precision recall f1-score support

 0 0.98 1.00 0.99 573597
 1 0.00 0.00 0.00 8895

 micro avg 0.98 0.98 0.98 582492
 macro avg 0.49 0.50 0.50 582492
weighted avg 0.97 0.98 0.98 582492

Out[47]: array([[573597, 0],
 [ 8895, 0]])

In [23]:
rf_evaluator_accuracy = evaluation.MulticlassClassificationEvaluator(labelCol="CANCELLED", metricName="accuracy")
rf_evaluator_accuracy.evaluate(rf_transform)

In [24]:
rf_bce = BinaryClassificationEvaluator(labelCol='CANCELLED', metricName='areaUnderROC')
rf_bce.evaluate(rf_transform)

Out[19]: 0.8826360414040805

In [25]:
randomForest_model.featureImportances.toArray()

Out[25]: array([0.09693428, 0.02103434, 0.04248902, ..., 0.01811722, 0.00213839,
 0.23430568])

In [26]:
randomForest_model = rf_model.stages[-1]
featureImportance_RF = pd.DataFrame(list(zip(inputColumns, randomForest_model.featureImportances.toArray())),
             columns = ['column', 'weight']).sort_values('weight', ascending=False)

In [27]:
ax1 = sns.barplot(x='weight', y='column', data=featureImportance_RF)
ax1.set(xlabel='Importance', ylabel='Features')
display()

In [28]:
gbt = GBTClassifier(featuresCol='features', labelCol='CANCELLED')
gbt_pipeline = Pipeline(stages=[va, gbt])
gbt_model = gbt_pipeline.fit(combined_df_2)
gbt_transform = gbt_model.transform(testing_df)

--------------------------------------------------------------------------- 
 Py4JJavaError Traceback (most recent call last)
 <command-2856938098060162> in <module> 
 1 gbt = GBTClassifier ( featuresCol = 'features' , labelCol = 'CANCELLED' ) 
 2 gbt_pipeline = Pipeline ( stages = [ va , gbt ] ) 
 ----> 3 gbt_model = gbt_pipeline . fit ( combined_df_2 ) 
 4 gbt_transform = gbt_model . transform ( testing_df ) 

 /databricks/spark/python/pyspark/ml/base.py in fit (self, dataset, params) 
 130 return self . copy ( params ) . _fit ( dataset ) 
 131 else : 
 --> 132 return self . _fit ( dataset ) 
 133 else : 
 134 raise ValueError("Params must be either a param map or a list/tuple of param maps, "

 /databricks/spark/python/pyspark/ml/pipeline.py in _fit (self, dataset) 
 107 dataset = stage . transform ( dataset ) 
 108 else : # must be an Estimator 
 --> 109 model = stage . fit ( dataset ) 
 110 transformers . append ( model ) 
 111 if i < indexOfLastEstimator : 

 /databricks/spark/python/pyspark/ml/base.py in fit (self, dataset, params) 
 130 return self . copy ( params ) . _fit ( dataset ) 
 131 else : 
 --> 132 return self . _fit ( dataset ) 
 133 else : 
 134 raise ValueError("Params must be either a param map or a list/tuple of param maps, "

 /databricks/spark/python/pyspark/ml/wrapper.py in _fit (self, dataset) 
 293 
 294 def _fit ( self , dataset ) : 
 --> 295 java_model = self . _fit_java ( dataset ) 
 296 model = self . _create_model ( java_model ) 
 297 return self . _copyValues ( model ) 

 /databricks/spark/python/pyspark/ml/wrapper.py in _fit_java (self, dataset) 
 290 """
 291 self . _transfer_params_to_java ( ) 
 --> 292 return self . _java_obj . fit ( dataset . _jdf ) 
 293 
 294 def _fit ( self , dataset ) : 

 /databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__ (self, *args) 
 1255 answer = self . gateway_client . send_command ( command ) 
 1256 return_value = get_return_value(
 -> 1257 answer, self.gateway_client, self.target_id, self.name)
 1258 
 1259 for temp_arg in temp_args : 

 /databricks/spark/python/pyspark/sql/utils.py in deco (*a, **kw) 
 61 def deco ( * a , ** kw ) : 
 62 try : 
 ---> 63 return f ( * a , ** kw ) 
 64 except py4j . protocol . Py4JJavaError as e : 
 65 s = e . java_exception . toString ( ) 

 /databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value (answer, gateway_client, target_id, name) 
 326 raise Py4JJavaError(
 327 "An error occurred while calling {0}{1}{2}.\n" . 
 --> 328 format(target_id, ".", name), value)
 329 else : 
 330 raise Py4JError(

 Py4JJavaError : An error occurred while calling o8970.fit.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 352.0 failed 1 times, most recent failure: Lost task 1.0 in stage 352.0 (TID 3531, localhost, executor driver): ExecutorLostFailure (executor driver exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 278328 ms
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:2362)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2350)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2349)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2349)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1102)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1102)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1102)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGSch

In [29]:
gbt_bce = BinaryClassificationEvaluator(labelCol='CANCELLED',metricName='areaUnderROC')
gbt_bce.evaluate(gbt_transform)

Out[15]: 0.9774463186766368

In [30]:
plt.figure(figsize=(5,5))
plt.plot([0, 1], [0, 1], 'r--')
plt.scatter(gbt_model.stages[-1].summary.roc.select('FPR').collect(),
            gbt_model.stages[-1].summary.roc.select('TPR').collect())
plt.title('ROC Scatter Plot : TPR/FPR')
plt.xlabel('FPR')
plt.ylabel('TPR')
display()

--------------------------------------------------------------------------- 
 AttributeError Traceback (most recent call last)
 <command-2795822308928804> in <module> 
 1 plt . figure ( figsize = ( 5 , 5 ) ) 
 2 plt . plot ( [ 0 , 1 ] , [ 0 , 1 ] , 'r--' ) 
 ----> 3 plt.scatter(gbt_model.stages[-1].summary.roc.select('FPR').collect(),
 4 gbt_model.stages[-1].summary.roc.select('TPR').collect())
 5 plt . title ( 'ROC Scatter Plot : TPR/FPR' ) 

 AttributeError : 'GBTClassificationModel' object has no attribute 'summary'

In [31]:
boost_model = gbt_model.stages[-1]
pd.DataFrame(list(zip(flights_df.columns[:20], boost_model.featureImportances.toArray())),
             columns = ['column', 'weight']).sort_values('weight', ascending=False)

--------------------------------------------------------------------------- 
 NameError Traceback (most recent call last)
 <command-4448974923366490> in <module> 
 ----> 1 boost_model = gbt_model . stages [ - 1 ] 
 2 pd.DataFrame(list(zip(flights_df.columns[:20], boost_model.featureImportances.toArray())),
 3 columns = ['column', 'weight']).sort_values('weight', ascending=False)

 NameError : name 'gbt_model' is not defined

In [32]:
predictions_train = gbt_transform
y_true = predictions_train.select(['CANCELLED']).collect()
y_pred = predictions_train.select(['prediction']).collect()

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_true, y_pred))
confusion_matrix(y_true, y_pred)

precision recall f1-score support

 0 1.00 0.95 0.97 573597
 1 0.22 0.95 0.36 8895

 micro avg 0.95 0.95 0.95 582492
 macro avg 0.61 0.95 0.67 582492
weighted avg 0.99 0.95 0.96 582492

Out[17]: array([[543559, 30038],
 [ 401, 8494]])

In [33]:
gbt_evaluator_f1 = evaluation.MulticlassClassificationEvaluator(labelCol="CANCELLED", metricName="f1")
gbt_evaluator_f1.evaluate(gbt_transform)

In [34]:
gbt_evaluator_accuracy = evaluation.MulticlassClassificationEvaluator(labelCol="CANCELLED", metricName="accuracy")
gbt_evaluator_accuracy.evaluate(gbt_transform)

Out[18]: 0.9477434883225864

In [35]:
gbt_evaluator_precision = evaluation.MulticlassClassificationEvaluator(labelCol="CANCELLED", metricName="weightedPrecision")
gbt_evaluator_precision.evaluate(gbt_transform)

In [36]:
gbt_evaluator_recall = evaluation.MulticlassClassificationEvaluator(labelCol="CANCELLED", metricName="weightedRecall")
gbt_evaluator_recall.evaluate(gbt_transform)